events {
    worker_connections 1024;
}

http {
    include mime.types;
    server {
        listen 80;
        listen [::]:80;

        location / {
            root /app/dist/client;
            try_files $uri /index.html;
            add_header Access-Control-Allow-Origin *;
        }
    }
}