ARG NODE_VERSION=18

FROM node:18-buster as base

WORKDIR /app

FROM base as builder

COPY packages/server/package.json yarn.lock ./
COPY packages/server/dist/ ./dist
RUN yarn install --frozen-lockfile

CMD [ "yarn", "preview"]