ARG NODE_VERSION=20
ARG CLIENT_PORT=3030

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

# # Копирование файла конфигурации Sequelize
# COPY packages/client/config/config.json ./config/config.json
# # Выполнение миграций
# RUN npx sequelize-cli db:migrate

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/client/dist/ && yarn build --scope=client


FROM nginx:latest as production
WORKDIR /app

COPY --from=builder /app/packages/client/dist/ /app/
COPY --from=builder /app/packages/client/nginx.conf /etc/nginx/nginx.conf

EXPOSE $CLIENT_PORT
CMD [ "nginx", "-g", "daemon off;" ]
