ARG NODE_VERSION

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY packages/client/package.json yarn.lock ./
COPY packages/client/dist/ ./dist
COPY packages/client/server ./server

RUN yarn install --frozen-lockfile

FROM nginx:latest
WORKDIR /app

COPY --from=builder /app /app
COPY packages/client/nginx.conf /etc/nginx/nginx.conf

CMD [ "nginx", "-g", "daemon off;"]
